---
- name: Add and Remove labels, annotations, and taints from all k3s nodes and masters
  hosts: k3s_all
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: merge all labels, annotations, and taints
      set_fact:
        merged_add_labels: "{{ lookup('community.general.merge_variables', '^k3s_add_labels_.+$') | default([], true) }}"
        merged_add_annotations: "{{ lookup('community.general.merge_variables', '^k3s_add_annotations_.+$') | default([], true) }}"
        merged_add_taints: "{{ lookup('community.general.merge_variables', '^k3s_add_taints_.+$') | default([], true) }}"

    - name: Add labels to k3s_node and k3s_master
      ansible.builtin.shell: |
        set -o pipefail

        export KUBECONFIG=/share/kubeconfig
        # Add labels
        kubectl label node {{ inventory_hostname.split('.')[0] }} {{ item }} --overwrite
      args:
        executable: /bin/bash
      changed_when: false
      delegate_to: manager
      loop: "{{ merged_add_labels }}"

    - name: Add annotations to k3s_node and k3s_master
      ansible.builtin.shell: |
        set -o pipefail

        export KUBECONFIG=/share/kubeconfig
        # Add annotations
        kubectl annotate node {{ inventory_hostname.split('.')[0] }} {{ item }} --overwrite
      args:
        executable: /bin/bash
      changed_when: false
      delegate_to: manager
      loop: "{{ merged_add_annotations }}"

    - name: Add taints to k3s_node and k3s_master
      ansible.builtin.shell: |
        set -o pipefail

        export KUBECONFIG=/share/kubeconfig
        # Add taints
        kubectl taint node {{ inventory_hostname.split('.')[0] }} {{ item }} --overwrite
      args:
        executable: /bin/bash
      changed_when: false
      delegate_to: manager
      loop: "{{ merged_add_taints }}"
